---
- name: setup cockpit
  hosts: web
  become: true
  roles:
    - ansible-cockpit-master
  tasks:
    - name: setup users
      user:
          name: azure-user
          group: wheel
          password: $1$sha512$p4fDxyhGzA9ig4t11MmHD1
