---
- name: setup cockpit
  hosts: web
  become: true
  roles:
    - ansible-cockpit
  tasks:
    - name: setup users
      users:
          name: azure-user
          group: wheel
          password:
