---
- name: setup repos
  hosts: web
  become: true
  tasks:
  - name: Disable all repositories by default
    shell: subscription-manager repos --disable '*'


  - name: Enable rhel-7-server-rpms
    shell: subscription-manager repos --enable 'rhel-7-server-rpms'
           
