---
- name: Run Updates
  hosts: windows
  connection: winrm
  tasks:
  - name: windows updates running
    win_updates:
       category_names:
         - Application
         - CriticalUpdates
         - DefinitionUpdates
         - SecurityUpdates
         - Updates
       state: installed  
    reboot: yes
    reboot_timeout: 420
