---
- name: Run Updates on Terminal Servers then wait 7 mins
  hosts: windows
  connection: winrm
  tasks:
  - name: windows updates running
    win_updates:
      category_names:
        - Application
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - Updates
    reboot: yes
    reboot_timeout: 420
